### ISSUE TITLE
Problem Encounter While Collecting Physical Layer Data

### ISSUE THREAD

**Issue by misty-cs** [bastibl/gr-ieee802-15-4#73]
I am attempting to collect physical layer data (IQ data) using wime zigbee gnuradio project.  The setup involves two Zigbee devices connected to the laptop's ports,  and I am using XCTU software to facilitate communication between the two Zigbee devices.

![Screenshot from 2023-10-10 13-55-49](https://github.com/bastibl/gr-ieee802-15-4/assets/116988923/7f4c4f01-111d-4d8b-90fe-279983a14143)

However, I'm encountering an issue. I can observe messages between the two Zigbee devices in the "sensor.pcap" file using Wireshark, I'm unable to visualize this data in the QT GUI SINK; it remains empty. Additionally, when I attempt to collect physical layer data, the output of "bing.bin"  file is also empty.

My question is, how can I successfully collect IQ data after the "IEEE 802.15.4 oqpsk phy" layer block?

**Comment by bastibl** [comment]
First of all remove the throttle block. It should not be used with hardware.

The time domain plot probably doesn't show anything because it is connected to the TX port, but you are probably not sending anything. I assume the flowgraph receives something but doesn't transmit itself. If you want to record the received IQ stream, you have to attach to the SDR, i.e., UHD USRP Source.

The (additional) reason why there is nothing in your output file is probably because the Tag Share block stops the stream, since there are only few samples on its second input. Remove Tags Strobe and Tags Share and you should see data in the file.

**Comment by misty-cs** [comment]
![Screenshot from 2023-10-14 15-38-19](https://github.com/bastibl/gr-ieee802-15-4/assets/116988923/cc280b7f-0108-4de6-9298-22228219c7d8)
I've tried various approaches, but I'm unable to obtain any IQ data from this flowgraph. I've also attached the SDR with the following configurations:
![thumbnail_processed-E64C0BFB-3776-4E2E-9B93-DCD48B2B1BDB-4D732994-E93B-46CA-80C3-7C2A9A8C1363 (1)](https://github.com/bastibl/gr-ieee802-15-4/assets/116988923/78d0a8c5-7de2-4187-8e8c-3f27270ae3ca)

My objective is to gather physical layer data. Could you please offer any alternative suggestions for achieving this? Thank you in advance.

**Comment by bastibl** [comment]
Please see my previous reply and let me know if you didn't understand it or what exactly you tried. The flowgraph in your second post hast the same issue then the one in the first, i.e., you connect the File Sink, and the time domain block to TX (and not RX).

**Comment by misty-cs** [comment]
Thank you; it has been resolved.
